name: add_2_calendar
description: A really simple Flutter plugin to add events to each platform's default calendar.
version: 3.0.1
homepage: https://github.com/ja2375/add_2_calendar

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.javih.add_2_calendar
        pluginClass: Add2CalendarPlugin
      ios:
        pluginClass: Add2CalendarPlugin
